//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyAdminPanel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id { get; set; }
        public int StudentID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
