//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyAdminPanel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcademyDB : DbContext
    {
        public AcademyDB()
            : base("name=AcademyDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademyInfo> AcademyInfo { get; set; }
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
