//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyAdminPanel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<int> GroupID { get; set; }
        public System.DateTime StartDate { get; set; }
        public string photo { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
